"""
Convert 3D model from .obj format to .wrl with colors
"""

from __future__ import annotations

# Global imports
import logging
import re
import textwrap
from pathlib import Path

# Local imports
from ..easyeda.parameters_easyeda import Ee3dModel
from .parameters_kicad_footprint import Ki3dModel, Ki3dModelBase

VRML_HEADER = """#VRML V2.0 utf8
# 3D model generated by easyeda2kicad.py (https://github.com/uPesy/easyeda2kicad.py)
"""


def get_materials(obj_data: str) -> dict[str, dict[str, str | list[str]]]:
    material_regex = "newmtl .*?endmtl"
    matchs = re.findall(pattern=material_regex, string=obj_data, flags=re.DOTALL)

    materials = {}
    for match in matchs:
        material = {}
        material_id = None
        for value in match.splitlines():
            if value.startswith("newmtl"):
                material_id = value.split()[1]
            elif value.startswith("Ka"):
                material["ambient_color"] = value.split()[1:]
            elif value.startswith("Kd"):
                material["diffuse_color"] = value.split()[1:]
            elif value.startswith("Ks"):
                material["specular_color"] = value.split()[1:]
            elif value.startswith("d "):
                # EasyEDA uses d as transparency directly (0.0 = opaque, 1.0 = transparent),
                # which matches VRML transparency semantics — use value as-is.
                try:
                    material["transparency"] = str(round(float(value.split()[1]), 4))
                except (ValueError, IndexError):
                    material["transparency"] = "0"

        if material_id is not None:
            materials[material_id] = material
    return materials


def get_vertices(
    obj_data: str,
    offset_x: float = 0.0,
    offset_y: float = 0.0,
    offset_z: float = 0.0,
) -> list[str]:
    result = []
    for line in obj_data.splitlines():
        parts = line.split()
        if len(parts) < 4 or parts[0] != "v":
            continue
        x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
        result.append(
            " ".join(
                [
                    str(round((x + offset_x) / 2.54, 4)),
                    str(round((y + offset_y) / 2.54, 4)),
                    str(round((z + offset_z) / 2.54, 4)),
                ]
            )
        )
    return result


def _get_obj_bbox(
    raw_obj: str,
) -> tuple[tuple[float, float], tuple[float, float], tuple[float, float]] | None:
    """Returns ((x_min, x_max), (y_min, y_max), (z_min, z_max)) or None if no vertices."""
    x_vals, y_vals, z_vals = [], [], []
    for line in raw_obj.splitlines():
        parts = line.split()
        if len(parts) < 4 or parts[0] != "v":
            continue
        x_vals.append(float(parts[1]))
        y_vals.append(float(parts[2]))
        z_vals.append(float(parts[3]))

    if not x_vals:
        return None

    return (
        (min(x_vals), max(x_vals)),
        (min(y_vals), max(y_vals)),
        (min(z_vals), max(z_vals)),
    )


def compute_model_offset(model_3d: Ee3dModel) -> tuple[float, float, float]:
    """Offset (mm) that repositions the raw model onto the KiCad footprint origin:
    center XY on (0,0), put the bottom at z=0, then add the EasyEDA placement
    metadata (c_origin - canvas_origin). Baked into the WRL vertices AND into the
    STEP geometry so both land in the same place."""
    offset_x = offset_y = offset_z = 0.0
    bbox = _get_obj_bbox(model_3d.raw_obj) if model_3d.raw_obj else None
    if bbox:
        (x_min, x_max), (y_min, y_max), (z_min, _) = bbox
        offset_x = -(x_min + x_max) / 2.0
        offset_y = -(y_min + y_max) / 2.0
        offset_z = -z_min
    offset_x += model_3d.translation.x
    offset_y += model_3d.translation.y
    offset_z += model_3d.translation.z
    return offset_x, offset_y, offset_z


_STEP_NUMBER = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?"
_STEP_POINT_RE = re.compile(
    r"(CARTESIAN_POINT\s*\(\s*'[^']*'\s*,\s*\(\s*)"
    rf"({_STEP_NUMBER})(\s*,\s*)({_STEP_NUMBER})(\s*,\s*)({_STEP_NUMBER})"
    r"(\s*\)\s*\))",
    re.IGNORECASE,
)


def _format_step_number(value: float) -> str:
    text = f"{value:.6f}"
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    if text in ("", "-0", "0"):
        return "0.0"
    if "." not in text:
        text += ".0"
    return text


def apply_step_offset(step: bytes, offset_x: float, offset_y: float, offset_z: float) -> bytes:
    """Translate every 3D CARTESIAN_POINT in an ISO-10303-21 STEP file by the given
    millimetre offset — the same offset generate_wrl_model bakes into the WRL, so the
    STEP aligns to the KiCad footprint origin. Pure text rewrite (no CAD kernel needed);
    EasyEDA STEP geometry is flat, so a one-shot translation of all points is exact."""
    if (offset_x, offset_y, offset_z) == (0.0, 0.0, 0.0):
        return step
    offsets = (offset_x, offset_y, offset_z)

    def repl(match: re.Match) -> str:
        values = [float(match.group(i)) + offsets[k] for k, i in enumerate((2, 4, 6))]
        return (
            match.group(1)
            + _format_step_number(values[0]) + match.group(3)
            + _format_step_number(values[1]) + match.group(5)
            + _format_step_number(values[2]) + match.group(7)
        )

    return _STEP_POINT_RE.sub(repl, step.decode("latin-1")).encode("latin-1")


def generate_wrl_model(model_3d: Ee3dModel) -> Ki3dModel:
    if not model_3d.raw_obj:
        return Ki3dModel(
            translation=Ki3dModelBase(),
            rotation=Ki3dModelBase(),
            name=model_3d.name,
            raw_wrl=None,
        )

    materials = get_materials(obj_data=model_3d.raw_obj)

    # Center XY on (0,0), bottom at z=0, then EE placement offset (see
    # compute_model_offset). The identical offset is baked into the STEP on export.
    offset_x, offset_y, offset_z = compute_model_offset(model_3d)
    logging.debug(
        f"3D centering offset: X={offset_x:.2f} Y={offset_y:.2f} Z={offset_z:.2f}"
    )

    vertices = get_vertices(
        obj_data=model_3d.raw_obj,
        offset_x=offset_x,
        offset_y=offset_y,
        offset_z=offset_z,
    )

    raw_wrl = VRML_HEADER
    shapes = model_3d.raw_obj.split("usemtl")[1:]
    if not shapes:
        logging.warning(
            f"3D model '{model_3d.name}': OBJ has no 'usemtl' sections; no geometry exported"
        )
        return Ki3dModel(
            translation=Ki3dModelBase(),
            rotation=Ki3dModelBase(),
            name=model_3d.name,
            raw_wrl=None,
        )
    for shape in shapes:
        lines = shape.splitlines()
        material_name = lines[0].replace(" ", "")
        material = materials.get(material_name)
        if material is None:
            logging.warning(
                f"3D model material '{material_name}' not found, skipping shape"
            )
            continue
        index_counter = 0
        link_dict = {}
        coord_index = []
        points = []
        for line in lines[1:]:
            if line.strip() and line.split()[0] == "f":
                face = [int(tok.split("/")[0]) for tok in line.split()[1:]]
                face_index = []
                for index in face:
                    if index not in link_dict:
                        link_dict[index] = index_counter
                        face_index.append(str(index_counter))
                        points.append(vertices[index - 1])
                        index_counter += 1
                    else:
                        face_index.append(str(link_dict[index]))
                face_index.append("-1")
                coord_index.append(",".join(face_index) + ",")

        # ambientIntensity: VRML expects a scalar (0-1), not an RGB triplet.
        # Compute luminance from Ka using Rec.601 weights.
        try:
            ka = material.get("ambient_color", ["0.2", "0.2", "0.2"])
            ambient_intensity = round(
                0.299 * float(ka[0]) + 0.587 * float(ka[1]) + 0.114 * float(ka[2]), 4
            )
        except (ValueError, IndexError):
            ambient_intensity = 0.2

        transparency = material.get("transparency", "0")

        shape_str = textwrap.dedent(
            f"""
            Shape{{
                appearance Appearance {{
                    material  Material 	{{
                        diffuseColor {" ".join(material["diffuse_color"])}
                        specularColor {" ".join(material["specular_color"])}
                        ambientIntensity {ambient_intensity}
                        transparency {transparency}
                        shininess 0.5
                    }}
                }}
                geometry IndexedFaceSet {{
                    ccw TRUE
                    solid FALSE
                    coord DEF co Coordinate {{
                        point [
                            {(", ").join(points)}
                        ]
                    }}
                    coordIndex [
                        {"".join(coord_index)}
                    ]
                }}
            }}"""
        )

        raw_wrl += shape_str

    return Ki3dModel(
        translation=Ki3dModelBase(),
        rotation=Ki3dModelBase(),
        name=model_3d.name,
        raw_wrl=raw_wrl,
    )


def _log_obj_bbox(raw_obj: str) -> None:
    """Log the OBJ vertex bounding box at DEBUG level."""
    bbox = _get_obj_bbox(raw_obj)
    if not bbox:
        logging.debug("3D OBJ: no vertices found")
        return

    (x_min, x_max), (y_min, y_max), (z_min, z_max) = bbox
    logging.debug(
        "3D OBJ bbox: "
        f"X [{x_min:.6g} .. {x_max:.6g}] "
        f"Y [{y_min:.6g} .. {y_max:.6g}] "
        f"Z [{z_min:.6g} .. {z_max:.6g}]"
    )


class Exporter3dModelKicad:
    def __init__(self, model_3d: Ee3dModel | None):
        self.input = model_3d
        if model_3d and model_3d.raw_obj:
            _log_obj_bbox(model_3d.raw_obj)
        self.output = (
            generate_wrl_model(model_3d=model_3d)
            if model_3d and model_3d.raw_obj
            else None
        )
        self.output_step = model_3d.step if model_3d else None

    def export(self, output_dir: str, overwrite: bool = True) -> bool:
        """Write WRL and STEP files into *output_dir* (the .3dshapes folder).

        EasyEDA always provides both OBJ (→WRL) and STEP for the same UUID.
        Returns False if files already exist and overwrite is False, True otherwise.
        """
        if not self.output:
            return False

        model_name = self.output.name
        output_path = Path(output_dir)
        wrl_path = output_path / f"{model_name}.wrl"
        step_path = output_path / f"{model_name}.step"

        if not overwrite and (wrl_path.exists() or step_path.exists()):
            logging.warning(f"3D model files already exist, skipping: {model_name}")
            return False

        output_path.mkdir(parents=True, exist_ok=True)

        if self.output.raw_wrl:
            wrl_path.write_text(self.output.raw_wrl, encoding="utf-8")

        if self.output_step:
            # Bake the same positioning offset into the STEP that generate_wrl_model
            # bakes into the WRL, so both align to the footprint origin and the
            # KiCad (model (offset)) can stay (0,0,0). Resolves the long-standing
            # "STEP misplaced relative to WRL" mismatch without a CAD kernel.
            step_bytes = self.output_step
            if self.input is not None and self.input.raw_obj:
                step_bytes = apply_step_offset(
                    step_bytes, *compute_model_offset(self.input)
                )
            step_path.write_bytes(step_bytes)

        return True
